export const APP_TEXT = {
  appTitle: 'Horarios escolares',
  backendStatus: {
    connected: 'Backend conectado',
    disconnected: 'Sin conexión',
    checking: 'Verificando conexión…',
  },
  health: {
    title: 'Estado del backend',
    description: 'Comprobación inicial de la conexión con la API.',
  },
  buttons: {
    retry: 'Reintentar',
  },
  nav: {
    salud: 'Estado del sistema',
    escuelas: 'Escuelas',
  },
  escuelas: {
    title: 'Gestión de escuelas',
    description: 'Consultá las escuelas cargadas y agregá nuevas.',
    listTitle: 'Escuelas cargadas',
    formTitle: 'Nueva escuela',
    labels: {
      nombre: 'Nombre de la escuela',
      tipo: 'Tipo de jornada',
      turno: 'Turno',
    },
    placeholders: {
      nombre: 'Ej: Escuela N.º 5',
    },
    selectPlaceholder: 'Seleccioná una opción',
    buttons: {
      crear: 'Crear escuela',
      creando: 'Creando…',
    },
    mensajes: {
      cargando: 'Cargando escuelas…',
      vacio: 'Todavía no hay escuelas cargadas.',
      errorListar: 'No se pudo obtener la lista de escuelas. Intentá nuevamente.',
      errorCrear: 'No se pudo crear la escuela. Revisá los datos e intentá de nuevo.',
      exitoCrear: 'Escuela creada correctamente.',
      camposRequeridos: 'Completá todos los campos antes de crear la escuela.',
    },
    tabla: {
      nombre: 'Nombre',
      tipo: 'Tipo',
      turno: 'Turno',
    },
    ayudaFilaClickeable: 'Hacé clic en una escuela para ver su detalle.',
    secciones: {
      bloques: 'Bloques horarios',
      grados: 'Grados',
      materias: 'Materias',
      docentes: 'Docentes',
      generarHorario: 'Generar horario',
    },
    detalle: {
      volver: 'Volver a escuelas',
      cargando: 'Cargando escuela…',
      errorCargar: 'No se pudo obtener la escuela solicitada.',
      noEncontrada: 'No encontramos esa escuela.',
      seccionesTitle: 'Secciones de la escuela',
      labels: {
        tipo: 'Tipo de jornada',
        turno: 'Turno',
      },
    },
  },
  bloques: {
    title: 'Bloques horarios',
    description: 'La grilla del día se repite igual toda la semana. Cargala una sola vez.',
    volver: 'Volver a la escuela',
    tabla: {
      orden: 'Orden',
      horaInicio: 'Hora inicio',
      horaFin: 'Hora fin',
      tipo: 'Tipo',
    },
    editor: {
      title: 'Cargar el día',
      ayuda: 'Agregá una fila por cada bloque del día, en el orden en que ocurren.',
    },
    labels: {
      horaInicio: 'Hora inicio',
      horaFin: 'Hora fin',
      tipo: 'Tipo de bloque',
    },
    selectPlaceholder: 'Seleccioná un tipo',
    buttons: {
      agregarFila: 'Agregar bloque',
      quitarFila: 'Quitar',
      guardarDia: 'Guardar día',
      guardando: 'Guardando…',
    },
    mensajes: {
      cargando: 'Cargando bloques…',
      errorListar: 'No se pudo obtener los bloques de esta escuela.',
      sinFilas: 'Agregá al menos un bloque antes de guardar.',
      camposIncompletos: 'Completá hora inicio, hora fin y tipo en todas las filas.',
      errorGuardar: 'No se pudo guardar el día. Revisá los datos e intentá de nuevo.',
      exitoGuardar: 'Día guardado correctamente.',
    },
  },
  grados: {
    title: 'Grados',
    description: 'Cargá los grados de esta escuela, con su maestra y cobertura de salida si corresponde.',
    volver: 'Volver a la escuela',
    ayudaCobertura:
      'La cobertura de salida es el día en que la maestra de grado se retira antes y un docente especial cubre el último módulo.',
    tabla: {
      nombre: 'Nombre',
      maestra: 'Maestra',
      cobertura: 'Cobertura de salida',
    },
    sinCobertura: 'Sin cobertura',
    editor: {
      title: 'Cargar grados',
      ayuda: 'Agregá una fila por cada grado de la escuela.',
    },
    labels: {
      nombre: 'Nombre del grado',
      maestra: 'Maestra',
      necesitaCobertura: 'Necesita cobertura de salida',
      diaCobertura: 'Día de cobertura',
    },
    placeholders: {
      nombre: 'Ej: 1.º A',
      maestra: 'Ej: Ana Pérez',
    },
    selectPlaceholder: 'Seleccioná un día',
    buttons: {
      agregarFila: 'Agregar grado',
      quitarFila: 'Quitar',
      guardarGrados: 'Guardar grados',
      guardando: 'Guardando…',
    },
    mensajes: {
      cargando: 'Cargando grados…',
      errorListar: 'No se pudo obtener los grados de esta escuela.',
      sinFilas: 'Agregá al menos un grado antes de guardar.',
      nombreRequerido: 'Completá el nombre en todas las filas.',
      diaCoberturaRequerido: 'Elegí un día de cobertura para los grados que la necesitan.',
      errorGuardar: 'No se pudo guardar los grados. Revisá los datos e intentá de nuevo.',
      exitoGuardar: 'Grados guardados correctamente.',
    },
  },
  materias: {
    title: 'Materias',
    description: 'Cargá el catálogo de materias y asigná cuántos módulos semanales tiene cada una por grado.',
    volver: 'Volver a la escuela',
    catalogo: {
      title: 'Materias de la escuela',
      vacio: 'Todavía no hay materias cargadas.',
      editorTitle: 'Agregar materias',
      editorAyuda: 'Agregá una fila por cada materia nueva.',
    },
    matriz: {
      title: 'Módulos por grado',
      ayuda: 'Ingresá los módulos semanales de cada materia en cada grado. Dejalo vacío si la materia no se dicta en ese grado.',
      faltanMaterias: 'Primero cargá las materias de la escuela.',
      faltanGrados: 'Esta escuela todavía no tiene grados cargados.',
      irAGrados: 'Ir a cargar grados',
      columnaGrado: 'Grado',
    },
    labels: {
      nombreMateria: 'Nombre de la materia',
    },
    placeholders: {
      nombreMateria: 'Ej: Música',
    },
    buttons: {
      agregarFila: 'Agregar materia',
      quitarFila: 'Quitar',
      guardarMaterias: 'Guardar materias',
      guardarModulos: 'Guardar módulos',
      guardando: 'Guardando…',
    },
    mensajes: {
      cargando: 'Cargando materias…',
      errorCargar: 'No se pudo obtener la información de materias de esta escuela.',
      sinFilas: 'Agregá al menos una materia antes de guardar.',
      nombreRequerido: 'Completá el nombre en todas las filas.',
      errorGuardarMaterias: 'No se pudo guardar las materias. Revisá los datos e intentá de nuevo.',
      exitoGuardarMaterias: 'Materias guardadas correctamente.',
      valorNegativo: 'Los módulos no pueden ser un número negativo.',
      sinCambiosModulos: 'No hay módulos nuevos para guardar.',
      errorGuardarModulos: 'No se pudo guardar los módulos. Revisá los datos e intentá de nuevo.',
      exitoGuardarModulos: 'Módulos guardados correctamente.',
    },
  },
  docentes: {
    title: 'Docentes',
    description: 'Cargá los docentes de la escuela y su disponibilidad horaria.',
    volver: 'Volver a la escuela',
    datos: {
      title: 'Docentes',
      faltanMaterias: 'Primero cargá las materias de la escuela: el docente necesita una materia asignada.',
      irAMaterias: 'Ir a cargar materias',
      vacio: 'Todavía no hay docentes cargados.',
      editorTitle: 'Agregar docentes',
      editorAyuda: 'Agregá una fila por cada docente nuevo.',
    },
    tabla: {
      nombre: 'Nombre',
      materia: 'Materia',
      cargo: 'Cargo (módulos)',
    },
    labels: {
      nombre: 'Nombre del docente',
      materia: 'Materia que dicta',
      cargo: 'Cargo (módulos semanales)',
    },
    placeholders: {
      nombre: 'Ej: Juan Gómez',
    },
    selectPlaceholder: 'Seleccioná una materia',
    disponibilidad: {
      title: 'Disponibilidad',
      ayuda:
        'Tildá los módulos en los que el docente puede dar clase. El generador de horarios usa esta información, así que es importante que esté completa.',
      faltanDocentes: 'Primero cargá los docentes de la escuela.',
      faltanBloques: 'Esta escuela todavía no tiene bloques horarios cargados.',
      irABloques: 'Ir a cargar bloques',
      elegirDocente: 'Elegí un docente',
      selectDocentePlaceholder: 'Seleccioná un docente',
      columnaBloque: 'Módulo',
      cargando: 'Cargando disponibilidad…',
    },
    buttons: {
      agregarFila: 'Agregar docente',
      quitarFila: 'Quitar',
      guardarDocentes: 'Guardar docentes',
      guardarDisponibilidad: 'Guardar disponibilidad',
      guardando: 'Guardando…',
    },
    mensajes: {
      cargando: 'Cargando docentes…',
      errorCargar: 'No se pudo obtener la información de docentes de esta escuela.',
      sinFilas: 'Agregá al menos un docente antes de guardar.',
      camposIncompletos: 'Completá nombre, materia y cargo en todas las filas.',
      cargoInvalido: 'El cargo no puede ser un número negativo.',
      errorGuardarDocentes: 'No se pudo guardar los docentes. Revisá los datos e intentá de nuevo.',
      exitoGuardarDocentes: 'Docentes guardados correctamente.',
      errorCargarDisponibilidad: 'No se pudo obtener la disponibilidad de este docente.',
      sinCambiosDisponibilidad: 'No hay disponibilidad nueva para guardar.',
      errorGuardarDisponibilidad: 'No se pudo guardar la disponibilidad. Revisá los datos e intentá de nuevo.',
      exitoGuardarDisponibilidad: 'Disponibilidad guardada correctamente.',
    },
  },
  generar: {
    title: 'Generar horario',
    description: 'Generá el horario a partir de los datos cargados: bloques, grados, materias y docentes.',
    volver: 'Volver a la escuela',
    estadoInicial: 'Todavía no se generó un horario para esta escuela.',
    confirmarRegenerar: 'Esto reemplazará el horario actual. ¿Querés continuar?',
    resultado: {
      title: 'Horario generado',
      columnaBloque: 'Módulo',
      celdaVacia: '—',
      pdfGrado: 'Descargar PDF',
      pdfDocentesTitle: 'Horarios por docente',
      pdfDocente: 'Descargar PDF',
    },
    buttons: {
      generar: 'Generar horario',
      regenerar: 'Regenerar horario',
      generando: 'Generando…',
    },
    mensajes: {
      cargando: 'Cargando información de la escuela…',
      errorCargar: 'No se pudo obtener la información de esta escuela.',
      errorGenerar: 'No se pudo generar el horario. Revisá los datos cargados e intentá de nuevo.',
      exitoGenerar: 'Horario generado correctamente.',
    },
  },
}

export const APP_COLORS = {
  primary: '#2563eb',
  primaryDark: '#1d4ed8',
  success: '#16a34a',
  error: '#dc2626',
  text: '#0f172a',
  textMuted: '#475569',
  background: '#f8fafc',
  surface: '#ffffff',
  border: '#e2e8f0',
}
